### ISSUE TITLE
Merging with another implementation of the datapackage standard

### ISSUE THREAD

**Issue by jhamrick** [trickvi/datapackage#10]
I wrote another interface for the datapackage standard, then discovered this version. I was thinking it might be nice for me to merge some of the features my version has into this one. I'm not sure if this is something you'd be interested in, or if you'd want to include all the features mine has, so I figure I'd post an issue first.

Here is my version: https://github.com/jhamrick/python-snippets/blob/master/snippets/datapackage.py

The features that mine has that this version doesn't include:

* It gives an interface for creating the datapackage (rather than just loading an existing one). This includes populating a bunch of default values, like the time created.
* When creating a datapackage, it automatically computes MD5 sums of the resources as well as determining the size in bytes and stores this information in `datapackage.json`.
* When loading a resource in a datapackage, it checks the size and (optionally) computes the MD5 sum and compares these against the values stored in `datapackage.json`, and throws an error if they do not match.
* It does some smart loading of different mimetypes -- it will load CSV files in as pandas dataframes, it will load npy files as numpy arrays, and it will load json files as a datastructure in memory (rather than the raw json string).
* It provides methods to increase version numbers according to semantic versioning.

Let me know if you're interested, and if so, I'll put together a pull request.

**Comment by pwalsh** [comment]
@trickvi can we close this one?

**Comment by trickvi** [comment]
Since this repo will not be the canonical datapackage repo this work should be redirected to the other repo if still valid.
