### ISSUE TITLE
Support other tabular formats apart csv

### ISSUE THREAD

**Issue by sabas** [trickvi/datapackage#11]
I created a (quasi) datapackage with two TSV files, and tried exploring with the python package, but I realized that only csv is supported (https://github.com/tryggvib/datapackage/blob/master/datapackage/datapackage.py#L263).
The spec got to beta10, but as I see there's a specification for csv dialects, it's possible to support it?

http://dataprotocols.org/tabular-data-package/
http://dataprotocols.org/csv-dialect/

**Comment by pwalsh** [comment]
@trickvi can we close this one? The new implementation uses `tabulator` which supports CSV, Excel, and table-like JSON, with scheduled support for ODS.

**Comment by trickvi** [comment]
The package will be maintained by the frictionlessdata project which as @pwalsh says uses a different way of reading resources so this can be considered fixed (in the new repo)
