### ISSUE TITLE
Inheritance for DataPackage and Resource objects

### ISSUE THREAD

**Issue by jhamrick** [trickvi/datapackage#18]
Both `DataPackage` and `Resource` objects share code for sources and licenses. Currently, this code is split off into separate modules, but it would probably be better to create a superclass that they inherit from and then possibly use mixins. See this comment thread:

https://github.com/jhamrick/datapackage/commit/01e53b62b7518d52340282b0b7be91e2963ecb81#commitcomment-7354250

**Comment by pwalsh** [comment]
@trickvi can we close this one?

**Comment by trickvi** [comment]
The package will be maintained by the frictionlessdata project where it has been developed from scratch so I'm closing this as it is no longer valid.
