### ISSUE TITLE
Getting resources from the datapackage

### ISSUE THREAD

**Issue by jhamrick** [trickvi/datapackage#20]
It looks like the ways to access the resources are currently:

* `DataPackage.resources`, which returns a list of `Resource` objects
* `DataPackage.get_resources()`, which returns a dictionary (but I'm not really sure what it's supposed to actually be doing, since it's not returning `Resource` objects?)

This means there isn't really an easy way to get a resource by name. I suggest removing `DataPackage.get_resources()`, and replacing it with `DataPackage.get_resource()`, which finds the resource with the matching name from `DataPackage.resources` and returns it.

**Comment by vitorbaptista** [comment]
In the new library (https://github.com/frictionlessdata/datapackage-py), there's no method to get a resource by its name. The resources are exposed as an array, so it's quite easy to do that with pure Python.

The current way of adding a resource to a datapackage is a bit different (check https://github.com/frictionlessdata/datapackage-py#creating-a-data-package), and I'm keen on hearing ideas on how to improve it. Please, open an issue on the other repository if you have some suggestion. Meanwhile, I suggest we close this issue.

**Comment by trickvi** [comment]
The package will be maintained by the frictionlessdata project so I'm closing this issue based on @vitorbaptista's comments
