### ISSUE TITLE
Getting data from a resource

### ISSUE THREAD

**Issue by jhamrick** [trickvi/datapackage#21]
The method `DataPackage.get_data` should probably be moved into the `Resource` class, and it should handle other data types (related to #11). Also, though, not all data types are necessarily tabular, so it might be good if we had two separate methods: one which loads in all the data at once, and one which iterates through the data (and throws an error if it's not tabular).

When the data is read in, the methods `update_bytes` and `update_hash` could optionally be called (I think they're currently not being used), and an error thrown if the data size or hash has changed.

**Comment by pwalsh** [comment]
@trickvi can we close this one? This is now supported for all data package types. When we have a tabular data package, you get a primed iterator to read the data stream, per resource.

**Comment by trickvi** [comment]
Closing this issue based on @pwalsh's comments
