### ISSUE TITLE
Integration with pandas

### ISSUE THREAD

**Issue by psychemedia** [trickvi/datapackage#22]
[*pandas*](https://github.com/pydata/pandas) seems to have quite a lot of traction at the moment, and provides a really powerful way of working with tabular datasets.

Having datapackage support as part of `pandas.io` could be really useful? Is anyone looking at getting datapackages into *pandas*?

**Comment by femtotrader** [comment]
Pandas shouldn't be a dependency.
If Pandas is installed and user wants a Pandas DataFrame he should get it but if Pandas is not installed (or user doesn't want DataFrame it should return raw Python type (list, dict, strings, ...)

**Comment by femtotrader** [comment]
See for example this

    # yahoo_daily.py

    import click

    import requests

    from pandas.compat import StringIO
    from pandas_datareader.utils import _sanitize_dates
    from delegate import Delegator

    _URL = 'http://ichart.finance.yahoo.com/table.csv'


    def get(sym, start, end, interval, delegate):
        """
        Get historical data for the given name from yahoo.
        Date format is datetime

        Returns a DataFrame.
        """
        start, end = _sanitize_dates(start, end)
        params = {
            's': sym,
            'a': start.month - 1,
            'b': start.day,
            'c': start.year,
            'd': end.month - 1,
            'e': end.day,
            'f': end.year,
            'g': interval,
            'ignore': '.csv'
        }
        response = requests.get(_URL, params=params)
        status_code = response.status_code
        if status_code == 200:
            dat = response.text

            with Delegator('pandas', delegate) as pd:
                if pd is not None:
                    df = pd.read_csv(StringIO(dat))
                    df = df.set_index("Date")
                    return df
                else:
                    return dat

        else:
            raise Exception("status_code=%d - it should be 200" % status_code)

    @click.command()
    @click.option('--delegate/--no-delegate', default=True)
    def main(delegate):
        result = get("AAPL", "2015-04-01", "2015-08-01", "d", delegate)
        print(result)
        print(type(result))

    if __name__ == "__main__":
        main()


    # delegate.py

    class Delegator(object):
        def __init__(self, s_module, delegate):
            self.s_module = s_module
            self.delegate = delegate

        def __enter__(self):
            try:
                if self.delegate:
                    i = __import__(self.s_module, fromlist=[''])
                    return i
                else:
                    return None
            except ImportError:
                return None

        def __exit__(self, *args):
            pass



    # =======


    $ python yahoo_daily.py --no-delegate

**Comment by vitorbaptista** [comment]
The new datapackage library (https://github.com/frictionlessdata/datapackage-py) doesn't explictly support exporting to Pandas as well. However, it should be easy to create a DataFrame from the dicts/lists that it exposes. Unless that flow is difficult, I'd rather keep the core tool simple.

I'm open for suggestions, though. Feel free to open an issue on https://github.com/frictionlessdata/datapackage-py about this and we can discuss over there. Meanwhile, I suggest we close this issue.

**Comment by femtotrader** [comment]
Maybe we should have a https://github.com/frictionlessdata/pandas-datapackage project which depends of https://github.com/frictionlessdata/datapackage-py

**Comment by vitorbaptista** [comment]
We do have a structure to import/export data to different storages (like BigQuery, SQLAlchemy, etc.). Pandas might be a special case, given it might be very simple to export, or maybe not. Regardless, I created a new issue to track this in https://github.com/frictionlessdata/datapackage-py/issues/73 so we can talk there and close this one.

**Comment by trickvi** [comment]
Since the package will be maintained by the frictionlessdata project where this issue is tracked I'm closing this issue.
