### ISSUE TITLE
Coping with dates

### ISSUE THREAD

**Issue by psychemedia** [trickvi/datapackage#24]
The example in the readme suggests running `datapkg = datapackage.DataPackage('http://data.okfn.org/data/cpi/')`.

The data contains a *year* column with dates of the form YYYY. The JSON file identifies the *year* column as type `date (yyyy)`.

When the datapackage is loaded in, a look at `datapkg.data` reveals rows containing things like:

     {'Year': datetime.date(2004, 1, 1), 'Country Code': 'AFG', 'Country Name': 'Afghanistan', 'CPI': 89.1695876693231}

Where did `datetime.date(2004, 1, 1)` come from? The year specified was `2004`. There is no day or month information? The best we can do from the imported data is return `datetime.date(2004, 1, 1).year` because the day and month are arbitrary and do not exist in the original data file. There is chance that the year could represent an actual date, but metadata would be required to identify the strike date to apply to the year?

A year more typically refers to a range of time, and any measures associated with a particular year are then likely to be summary statistics calculated over that range (although others may also be pointwise figures at a particular strike date, such as the first day of the year or the last day of the year, or the first trading day of the year, or the last trading day of the year etc).

It really concerns me that the datapackage loader can invent information not described by the datapackage data file, as interpreted by the datapackage metadat file?

**Comment by vitorbaptista** [comment]
The new library (https://github.com/frictionlessdata/datapackage-py) doesn't suffer from this issue. However, the year isn't parsed, returning as a string. I suggest we close this issue.

**Comment by trickvi** [comment]
Since the repo will be maintained by the frictionlessdata and developed from scratch where this is not an issue so I'm closing this issue.
