### ISSUE TITLE
Any interest in data package install / find API?

### ISSUE THREAD

**Issue by matthew-brett** [trickvi/datapackage#26]
Over on the mailing list for the nipy project, we need stuff for installing data packages locally, and providing an API to find them.  I'm wondering if y'all would be interested in this going into ``datapackage``?

Here's the draft with use cases and a proposal.  We will probably end up implementing something in one of our libraries if y'all think this isn't a match for ``datapackage``....

https://github.com/nipy/nibabel/wiki/data_packages

**Comment by vitorbaptista** [comment]
@matthew-brett We're migrating to a new library at https://github.com/frictionlessdata/datapackage-py. If you still have interest in doing this work, please open an issue there. It looks like a great addition!

Meanwhile, I suggest we close this.

**Comment by trickvi** [comment]
Yes @matthew-brett, the project will be maintained by the frictionlessdata project so any work should be done towards their version. Closing this issue.
