### ISSUE TITLE
Read any datapackage.json

### ISSUE THREAD

**Issue by pwalsh** [trickvi/datapackage#35]
As I discovered [here](https://github.com/tryggvib/datapackage/issues/34), the library is very strict in what it accepts as a Data Package. 

This is quite limiting, from two angles:

* The spec explicitly allows arbitrary properties:

> It MAY contain any number of attributes. All attributes at the first level not otherwise specified here are considered metadata attributes.

and

> NOTE: A Data Package author MAY add any number of additional fields beyond those listed in the specification here.

* I think there is a valid use case for a generic data package loader: meaning, load a data package descriptor, without needing to know what variant of a data package it is (Tabular Data Package, Budget Data Package, etc.)
    * The use case that I have for this now is: I have some code that reads resources from a Data Package: for this code, it does not matter what type of Data Package it is: it just needs to get all the resources referenced in said data package.

WDYT?

**Comment by tryggvib** [comment]
I think it is a problem that the library is so strict. That's not standard compliant. So we need to fix this.

**Comment by pwalsh** [comment]
It seems that the already existing EXTENDABLE constant is designed for this.

**Comment by pwalsh** [comment]
@trickvi can we close this one?

**Comment by vitorbaptista** [comment]
The new datapackage library (https://github.com/frictionlessdata/datapackage-py) doesn't suffer from this issue, because it validates using the actual JSON Schema. It's as strict as the schema dictates it to be. We can close this, then.

**Comment by trickvi** [comment]
Since the repo will be maintained by the frictionlessdata where it is solved so I'm closing this issue.
