### ISSUE TITLE
Travis-CI badge

### ISSUE THREAD

**Issue by femtotrader** [trickvi/datapackage#46]
Hello,

It will be nice to add a Travis-CI badge [![Build Status](https://travis-ci.org/trickvi/datapackage.svg?branch=master)](https://travis-ci.org/trickvi/datapackage)

> .. image:: https://travis-ci.org/trickvi/datapackage.svg?branch=master
>     :target: https://travis-ci.org/trickvi/datapackage

Kind regard

**Comment by trickvi** [comment]
I agree that this is a nice addition so I added it with 16b3ac2f7b6d0c1ea389673e79d633b9bbc9ed63

Thanks a lot. Now onwards to your other issues.
