### ISSUE TITLE
Array support seems incorrect

### ISSUE THREAD

**Issue by hozn** [trickvi/datapackage#53]
I might be misreading the [json table schema spec](http://dataprotocols.org/json-table-schema/), but it looks like an array is supposed to be a JSON array:

> array
>   array formats:
>  default: any valid JSON array. Equivalent to not declaring a format.

The current implementation attempts to naively cast the string value to a list; however, this produces unexpected results:
```
>>> list("['a', 'b', 'c']")
['[', "'", 'a', "'", ',', ' ', "'", 'b', "'", ',', ' ', "'", 'c', "'", ']']
```

**Comment by pwalsh** [comment]
@trickvi can we close this one?

**Comment by trickvi** [comment]
Since the repo will be maintained by the frictionlessdata and developed from scratch (this therefore not an issue) I'm closing this issue.
