### ISSUE TITLE
output a Pandas DataFrame with datapkg.dataframe

### ISSUE THREAD

**Issue by femtotrader** [trickvi/datapackage#56]
Hello,

I think you should add a method to output a Pandas DataFrame.

It should only be available when Pandas is installed.

I think this dataframe should be create a initialization.

Maybe you should use something like

    try:
        import pandas as pd
        _PANDAS_INSTALLED = True
    except ImportError:
        _PANDAS_INSTALLED = False

and use this _PANDAS_INSTALLED variable to know if Pandas is installed or not
and do something like

    def __init__(self):

        ...

        self._dataframe = None
        if _PANDAS_INSTALLED:
            try:
                self._dataframe = pd.DataFrame(list(self.data))
            except:
                pass
        else:
            self._dataframe = None

    @property
    def dataframe(self):
        if self._dataframe is not None:
            return self._dataframe
        else:
            raise NotImplementedError("Can't output a DataFrame because Pandas is not installed")

This is just an idea

Not sure if `pd.DataFrame(list(self.data))` is a great idea

Kind regards

**Comment by femtotrader** [comment]
see also https://github.com/blaze/odo/issues/317

**Comment by femtotrader** [comment]
see also https://github.com/trickvi/datapackage/issues/22

**Comment by trickvi** [comment]
Since the package will be maintained by the frictionlessdata work should take place there and pandas integration is tracked in frictionlessdata/datapackage-py#37 so I'm closing this issue.
