### ISSUE TITLE
Improve readability of DataPackage object (__str__)

### ISSUE THREAD

**Issue by femtotrader** [trickvi/datapackage#57]
Hello,

this

    In [60]: datapkg
    Out[60]:
    {'base': 'http://data.okfn.org/data/cpi/',
     'bugs': {'url': 'https://github.com/datasets/cpi/issues'},
     'description': 'Annual Consumer Price Index (CPI) for most countries in the world. Reference year is 2005.',
     'download_url': 'https://raw.githubusercontent.com/datasets/cpi/master/data/cpi.csv',
     'homepage': 'https://github.com/datasets/cpi',
     'id': 'cpi',
     'isCore': True,
     'keywords': ['CPI',
      'World',
      'Consumer Price Index',
      'Annual Data',
      'The World Bank'],
     'last_updated': '2014-09-22',
     'licenses': [{'type': 'ODC-PDDL',
       'url': 'http://opendatacommons.org/licenses/pddl/'}],
     'name': 'cpi',
     'owner': 'core',
     'readme': "# CPI datapackage\n\nAnnual Consumer Price Index (CPI) for most countries in the world when it has been measured. The reference year is 2005 (meaning the value of CPI for all countries is 100 and all other CPI values are relative to that year).\n\n# Data\n\nThe data comes from [The World Bank](http://data.worldbank.org/indicator/FP.CPI.TOTL) and is collected from 1960 to 2011. There are some values missing from data so users of the data will have to *guess* what should be in the empty slots.\n\nThe actual download happens via [The World Bank's API (with csv as the requested format)](http://api.worldbank.org/indicator/FP.CPI.TOTL?format=csv).\n\nIt is parsed via the script **cpi2datapackage.py**, located in scripts.\n\n## Usage of cpi2datapackage.py\n\n    usage: cpi2datapackage.py [-h] [-o filename] [source]\n    \n    convert WorldBank CPI data to a data package resource\n\n    positional arguments:\n      source                source file to generate output from\n    \n    optional arguments:\n      -h, --help            show this help message and exit\n      -o filename, --output filename\n                            define output filename\n",
     'readmeHtml': '<h1 id="cpi-datapackage">CPI datapackage</h1>\n<p>Annual Consumer Price Index (CPI) for most countries in the world when it has been measured. The reference year is 2005 (meaning the value of CPI for all countries is 100 and all other CPI values are relative to that year).</p>\n<h1 id="data">Data</h1>\n<p>The data comes from <a href="http://data.worldbank.org/indicator/FP.CPI.TOTL">The World Bank</a> and is collected from 1960 to 2011. There are some values missing from data so users of the data will have to <em>guess</em> what should be in the empty slots.</p>\n<p>The actual download happens via <a href="http://api.worldbank.org/indicator/FP.CPI.TOTL?format=csv">The World Bank&#39;s API (with csv as the requested format)</a>.</p>\n<p>It is parsed via the script <strong>cpi2datapackage.py</strong>, located in scripts.</p>\n<h2 id="usage-of-cpi2datapackage-py">Usage of cpi2datapackage.py</h2>\n<pre><code>usage: cpi2datapackage.py [-h] [-o filename] [source]\n\nconvert WorldBank CPI data to a data package resource\n\npositional arguments:\n  source                source file to generate output from\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -o filename, --output filename\n                        define output filename\n</code></pre>',
     'readme_html': '<h1 id="cpi-datapackage">CPI datapackage</h1>\n<p>Annual Consumer Price Index (CPI) for most countries in the world when it has been measured. The reference year is 2005 (meaning the value of CPI for all countries is 100 and all other CPI values are relative to that year).</p>\n<h1 id="data">Data</h1>\n<p>The data comes from <a href="http://data.worldbank.org/indicator/FP.CPI.TOTL">The World Bank</a> and is collected from 1960 to 2011. There are some values missing from data so users of the data will have to <em>guess</em> what should be in the empty slots.</p>\n<p>The actual download happens via <a href="http://api.worldbank.org/indicator/FP.CPI.TOTL?format=csv">The World Bank&#39;s API (with csv as the requested format)</a>.</p>\n<p>It is parsed via the script <strong>cpi2datapackage.py</strong>, located in scripts.</p>\n<h2 id="usage-of-cpi2datapackage-py">Usage of cpi2datapackage.py</h2>\n<pre><code>usage: cpi2datapackage.py [-h] [-o filename] [source]\n\nconvert WorldBank CPI data to a data package resource\n\npositional arguments:\n  source                source file to generate output from\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -o filename, --output filename\n                        define output filename\n</code></pre>',
     'resources': [{'datapackage_uri': 'http://data.okfn.org/data/cpi/',
       'format': 'csv',
       'is_local': False,
       'mediatype': 'text/csv',
       'name': 'cpi',
       'schema': {'fields': [{'name': 'Country Name', 'type': 'string'},
         {'name': 'Country Code', 'type': 'string'},
         {'format': 'yyyy', 'name': 'Year', 'type': 'date'},
         {'description': 'CPI (where 2005=100)',
          'name': 'CPI',
          'type': 'number'}]},
       'url': 'https://raw.githubusercontent.com/datasets/cpi/master/data/cpi.csv'}],
     'sources': [{'name': 'The World Bank',
       'web': 'http://data.worldbank.org/indicator/FP.CPI.TOTL'}],
     'title': 'Annual Consumer Price Index (CPI)',
     'version': '2.0.0'}

is not very readable.

Maybe you might improve it using something like:

    import json
    print(json.dumps(datapkg, indent=4))

which returns

    {
        "id": "cpi",
        "readmeHtml": "<h1 id=\"cpi-datapackage\">CPI datapackage</h1>\n<p>Annual Consumer Price Index (CPI) for most countries in the world when it has been measured. The reference year is 2005 (meaning the value of CPI for all countries is 100 and all other CPI values are relative to that year).</p>\n<h1 id=\"data\">Data</h1>\n<p>The data comes from <a href=\"http://data.worldbank.org/indicator/FP.CPI.TOTL\">The World Bank</a> and is collected from 1960 to 2011. There are some values missing from data so users of the data will have to <em>guess</em> what should be in the empty slots.</p>\n<p>The actual download happens via <a href=\"http://api.worldbank.org/indicator/FP.CPI.TOTL?format=csv\">The World Bank&#39;s API (with csv as the requested format)</a>.</p>\n<p>It is parsed via the script <strong>cpi2datapackage.py</strong>, located in scripts.</p>\n<h2 id=\"usage-of-cpi2datapackage-py\">Usage of cpi2datapackage.py</h2>\n<pre><code>usage: cpi2datapackage.py [-h] [-o filename] [source]\n\nconvert WorldBank CPI data to a data package resource\n\npositional arguments:\n  source                source file to generate output from\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -o filename, --output filename\n                        define output filename\n</code></pre>",
        "licenses": [
            {
                "url": "http://opendatacommons.org/licenses/pddl/",
                "type": "ODC-PDDL"
            }
        ],
        "isCore": true,
        "keywords": [
            "CPI",
            "World",
            "Consumer Price Index",
            "Annual Data",
            "The World Bank"
        ],
        "owner": "core",
        "title": "Annual Consumer Price Index (CPI)",
        "last_updated": "2014-09-22",
        "base": "http://data.okfn.org/data/cpi/",
        "bugs": {
            "url": "https://github.com/datasets/cpi/issues"
        },
        "sources": [
            {
                "web": "http://data.worldbank.org/indicator/FP.CPI.TOTL",
                "name": "The World Bank"
            }
        ],
        "readme_html": "<h1 id=\"cpi-datapackage\">CPI datapackage</h1>\n<p>Annual Consumer Price Index (CPI) for most countries in the world when it has been measured. The reference year is 2005 (meaning the value of CPI for all countries is 100 and all other CPI values are relative to that year).</p>\n<h1 id=\"data\">Data</h1>\n<p>The data comes from <a href=\"http://data.worldbank.org/indicator/FP.CPI.TOTL\">The World Bank</a> and is collected from 1960 to 2011. There are some values missing from data so users of the data will have to <em>guess</em> what should be in the empty slots.</p>\n<p>The actual download happens via <a href=\"http://api.worldbank.org/indicator/FP.CPI.TOTL?format=csv\">The World Bank&#39;s API (with csv as the requested format)</a>.</p>\n<p>It is parsed via the script <strong>cpi2datapackage.py</strong>, located in scripts.</p>\n<h2 id=\"usage-of-cpi2datapackage-py\">Usage of cpi2datapackage.py</h2>\n<pre><code>usage: cpi2datapackage.py [-h] [-o filename] [source]\n\nconvert WorldBank CPI data to a data package resource\n\npositional arguments:\n  source                source file to generate output from\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -o filename, --output filename\n                        define output filename\n</code></pre>",
        "description": "Annual Consumer Price Index (CPI) for most countries in the world. Reference year is 2005.",
        "download_url": "https://raw.githubusercontent.com/datasets/cpi/master/data/cpi.csv",
        "readme": "# CPI datapackage\n\nAnnual Consumer Price Index (CPI) for most countries in the world when it has been measured. The reference year is 2005 (meaning the value of CPI for all countries is 100 and all other CPI values are relative to that year).\n\n# Data\n\nThe data comes from [The World Bank](http://data.worldbank.org/indicator/FP.CPI.TOTL) and is collected from 1960 to 2011. There are some values missing from data so users of the data will have to *guess* what should be in the empty slots.\n\nThe actual download happens via [The World Bank's API (with csv as the requested format)](http://api.worldbank.org/indicator/FP.CPI.TOTL?format=csv).\n\nIt is parsed via the script **cpi2datapackage.py**, located in scripts.\n\n## Usage of cpi2datapackage.py\n\n    usage: cpi2datapackage.py [-h] [-o filename] [source]\n    \n    convert WorldBank CPI data to a data package resource\n\n    positional arguments:\n      source                source file to generate output from\n    \n    optional arguments:\n      -h, --help            show this help message and exit\n      -o filename, --output filename\n                            define output filename\n",
        "version": "2.0.0",
        "resources": [
            {
                "datapackage_uri": "http://data.okfn.org/data/cpi/",
                "mediatype": "text/csv",
                "name": "cpi",
                "format": "csv",
                "is_local": false,
                "schema": {
                    "fields": [
                        {
                            "name": "Country Name",
                            "type": "string"
                        },
                        {
                            "name": "Country Code",
                            "type": "string"
                        },
                        {
                            "format": "yyyy",
                            "name": "Year",
                            "type": "date"
                        },
                        {
                            "description": "CPI (where 2005=100)",
                            "name": "CPI",
                            "type": "number"
                        }
                    ]
                },
                "url": "https://raw.githubusercontent.com/datasets/cpi/master/data/cpi.csv"
            }
        ],
        "name": "cpi",
        "homepage": "https://github.com/datasets/cpi"
    }

or

    import yaml
    print(yaml.dump(datapkg, indent=4))

which returns

    !!python/object/new:datapackage.datapackage.DataPackage
    dictitems:
        base: http://data.okfn.org/data/cpi/
        bugs: {url: 'https://github.com/datasets/cpi/issues'}
        description: Annual Consumer Price Index (CPI) for most countries in the world.
            Reference year is 2005.
        download_url: https://raw.githubusercontent.com/datasets/cpi/master/data/cpi.csv
        homepage: https://github.com/datasets/cpi
        id: cpi
        isCore: true
        keywords: [CPI, World, Consumer Price Index, Annual Data, The World Bank]
        last_updated: '2014-09-22'
        licenses:
        - !!python/object/new:datapackage.licenses.License
            dictitems: {type: ODC-PDDL, url: 'http://opendatacommons.org/licenses/pddl/'}
        name: cpi
        owner: core
        readme: "# CPI datapackage\n\nAnnual Consumer Price Index (CPI) for most countries\
            \ in the world when it has been measured. The reference year is 2005 (meaning\
            \ the value of CPI for all countries is 100 and all other CPI values are relative\
            \ to that year).\n\n# Data\n\nThe data comes from [The World Bank](http://data.worldbank.org/indicator/FP.CPI.TOTL)\
            \ and is collected from 1960 to 2011. There are some values missing from data\
            \ so users of the data will have to *guess* what should be in the empty slots.\n\
            \nThe actual download happens via [The World Bank's API (with csv as the requested\
            \ format)](http://api.worldbank.org/indicator/FP.CPI.TOTL?format=csv).\n\n\
            It is parsed via the script **cpi2datapackage.py**, located in scripts.\n\n\
            ## Usage of cpi2datapackage.py\n\n    usage: cpi2datapackage.py [-h] [-o filename]\
            \ [source]\n    \n    convert WorldBank CPI data to a data package resource\n\
            \n    positional arguments:\n      source                source file to generate\
            \ output from\n    \n    optional arguments:\n      -h, --help           \
            \ show this help message and exit\n      -o filename, --output filename\n\
            \                            define output filename\n"
        readmeHtml: "<h1 id=\"cpi-datapackage\">CPI datapackage</h1>\n<p>Annual Consumer\
            \ Price Index (CPI) for most countries in the world when it has been measured.\
            \ The reference year is 2005 (meaning the value of CPI for all countries is\
            \ 100 and all other CPI values are relative to that year).</p>\n<h1 id=\"\
            data\">Data</h1>\n<p>The data comes from <a href=\"http://data.worldbank.org/indicator/FP.CPI.TOTL\"\
            >The World Bank</a> and is collected from 1960 to 2011. There are some values\
            \ missing from data so users of the data will have to <em>guess</em> what\
            \ should be in the empty slots.</p>\n<p>The actual download happens via <a\
            \ href=\"http://api.worldbank.org/indicator/FP.CPI.TOTL?format=csv\">The World\
            \ Bank&#39;s API (with csv as the requested format)</a>.</p>\n<p>It is parsed\
            \ via the script <strong>cpi2datapackage.py</strong>, located in scripts.</p>\n\
            <h2 id=\"usage-of-cpi2datapackage-py\">Usage of cpi2datapackage.py</h2>\n\
            <pre><code>usage: cpi2datapackage.py [-h] [-o filename] [source]\n\nconvert\
            \ WorldBank CPI data to a data package resource\n\npositional arguments:\n\
            \  source                source file to generate output from\n\noptional arguments:\n\
            \  -h, --help            show this help message and exit\n  -o filename, --output\
            \ filename\n                        define output filename\n</code></pre>"
        readme_html: "<h1 id=\"cpi-datapackage\">CPI datapackage</h1>\n<p>Annual Consumer\
            \ Price Index (CPI) for most countries in the world when it has been measured.\
            \ The reference year is 2005 (meaning the value of CPI for all countries is\
            \ 100 and all other CPI values are relative to that year).</p>\n<h1 id=\"\
            data\">Data</h1>\n<p>The data comes from <a href=\"http://data.worldbank.org/indicator/FP.CPI.TOTL\"\
            >The World Bank</a> and is collected from 1960 to 2011. There are some values\
            \ missing from data so users of the data will have to <em>guess</em> what\
            \ should be in the empty slots.</p>\n<p>The actual download happens via <a\
            \ href=\"http://api.worldbank.org/indicator/FP.CPI.TOTL?format=csv\">The World\
            \ Bank&#39;s API (with csv as the requested format)</a>.</p>\n<p>It is parsed\
            \ via the script <strong>cpi2datapackage.py</strong>, located in scripts.</p>\n\
            <h2 id=\"usage-of-cpi2datapackage-py\">Usage of cpi2datapackage.py</h2>\n\
            <pre><code>usage: cpi2datapackage.py [-h] [-o filename] [source]\n\nconvert\
            \ WorldBank CPI data to a data package resource\n\npositional arguments:\n\
            \  source                source file to generate output from\n\noptional arguments:\n\
            \  -h, --help            show this help message and exit\n  -o filename, --output\
            \ filename\n                        define output filename\n</code></pre>"
        resources:
        - !!python/object/new:datapackage.resource.Resource
            dictitems:
                datapackage_uri: http://data.okfn.org/data/cpi/
                format: csv
                is_local: false
                mediatype: text/csv
                name: cpi
                schema:
                    fields:
                    - {name: Country Name, type: string}
                    - {name: Country Code, type: string}
                    - {format: yyyy, name: Year, type: date}
                    - {description: CPI (where 2005=100), name: CPI, type: number}
                url: https://raw.githubusercontent.com/datasets/cpi/master/data/cpi.csv
        sources:
        - !!python/object/new:datapackage.sources.Source
            dictitems: {name: The World Bank, web: 'http://data.worldbank.org/indicator/FP.CPI.TOTL'}
        title: Annual Consumer Price Index (CPI)
        version: 2.0.0

or using `pprint` https://docs.python.org/2/library/pprint.html

Kind regards

**Comment by pwalsh** [comment]
@trickvi can we close this one?
