### ISSUE TITLE
Convert JSON Table Schema to DataShape

### ISSUE THREAD

**Issue by femtotrader** [trickvi/datapackage#60]
Hello,

I wonder if any work has been done to convert JSON Table Schema to DataShape.
http://odo.pydata.org/en/latest/datashape.html
http://datashape.pydata.org/

It will greatly help to make DataPackages "odo"-izable
https://github.com/blaze/odo/issues/317

    import datapackage
    # Note trailing slash is important for data.okfn.org
    datapkg = datapackage.DataPackage('http://data.okfn.org/data/cpi/')
    In [145]: datapkg.resources[0].schema['fields']
    Out[145]:
    [{'name': 'Country Name', 'type': 'string'},
     {'name': 'Country Code', 'type': 'string'},
     {'format': 'yyyy', 'name': 'Year', 'type': 'date'},
     {'description': 'CPI (where 2005=100)', 'name': 'CPI', 'type': 'number'}]

Auto `discover` after converting to a DataFrame returns

    In [150]: from odo import discover

    In [151]: discover(pd.DataFrame(list(datapkg.get_data(datapkg.resources[0]))))
    Out[151]:
    dshape("""6748 * {
      CPI: ?float64,
      'Country Code': ?string,
      'Country Name': ?string,
      Year: ?string
      }""")

I also noticed that

    In [153]: type(datapkg.resources[0].schema)
    Out[153]: dict

Maybe `schema` should return an object instead of a dict

Kind regards

**Comment by femtotrader** [comment]
Some code

    #http://dataprotocols.org/json-table-schema/
    import warnings

    def field_type(typ, missing=False):
        if missing:
            s_missing = '?'
        else:
            s_missing = ''
        D_TYPES =  {
            'number': 'float64',
            'string': 'string'
        }
        TYP_DEFAULT = 'string'
        try:
            return s_missing + D_TYPES[typ]
        except KeyError:
            msg = "Can't find type %r - using %r" % (typ, TYP_DEFAULT)
            warnings.warn(msg)
            return s_missing + TYP_DEFAULT

    def json_table_schema_to_datashape(schema, indent="  ", line_feed="\n"):
        s = 'var * {' + line_feed
        for i, field in enumerate(schema['fields']):
            if i != 0:
                s += ',' + line_feed
            s += indent + "%r: %s" % (field['name'], field_type(field['type'], missing=True))
        s += line_feed + '}'
        return s

We can use it using

    ds = json_table_schema_to_datashape(datapkg.resources[0].schema)
    print(ds)

it should display

    var * {
      'Country Name': ?string,
      'Country Code': ?string,
      'Year': ?string,
      'CPI': ?float64
    }

We probably need to improve this `D_TYPES`dictionary.

If `datapkg.resources[0].schema` was an object we could add a method for this

**Comment by pwalsh** [comment]
https://github.com/okfn/jsontableschema-py

**Comment by femtotrader** [comment]
Is this project `okfn/jsontableschema-py` being used in `trickvi/datapackage` ?

**Comment by pwalsh** [comment]
It is not, it is more recent than `datapackage`. I was just pointing out that we have a lib in Python that works with JSON Table Schema.

**Comment by femtotrader** [comment]
A project to convert a JSON Table Schema <--> Datashape is available here
https://github.com/okfn/jts-datashape
So I'm closing this issue.
