### ISSUE TITLE
Datapackage should have some tests with the whole content of datasets

### ISSUE THREAD

**Issue by femtotrader** [trickvi/datapackage#63]
Hello,

I think that Datapackage should have some tests with the whole content of 
https://github.com/datasets/

for example I noticed manually that:

```
datapackage.DataPackage("https://raw.githubusercontent.com/datasets/gold-prices/master/")
```

raises 

```
ValueError: License type is missing
```

maybe we should expect to have set it to `None`
(see https://github.com/trickvi/datapackage/issues/64 )

This kind of tests could be disabled for Continuous Integration (because that's quite big to download, and quite long to process).

This kind of tests should only be run with a cache mechanism like what I requested in
https://github.com/trickvi/datapackage/issues/61 and what I implemented in https://github.com/trickvi/datapackage/pull/62

A list of Datapackages is available at https://github.com/datasets/registry
but it's not readable using `trickvi/datapackage` see

```
datapackage.DataPackage("https://raw.githubusercontent.com/datasets/registry/master/")
```

it raises

```
HTTPError: HTTP Error 404: Not Found
```

because there is no `datapackage.json` see https://github.com/datasets/registry/issues/112

An other related issue is that datapackage is not able to accept GitHub repository.
https://github.com/trickvi/datapackage/issues/65 and (unfortunately) https://github.com/datasets/registry contains only GitHub repository, not URL to directory which contains datapackage.json or URL to datapackage.json (see https://github.com/datasets/registry/issues/113 )

Kind regards

**Comment by femtotrader** [comment]
```
import click

import warnings

import requests
import datapackage
import requests_cache
import datetime

import re
import traceback

import pandas as pd

URL_DEFAULT = 'https://raw.githubusercontent.com/datasets/registry/master'

def fix_url(url):
    pattern = "https:\/\/github.com\/(.*)\/(.*)"
    m = re.match(pattern, url)
    if m is not None:
        (user, project) = m.groups()
        return "https://raw.githubusercontent.com/%s/%s/master/" % (user, project)

    return url

@click.command()
@click.option('--cache/--no-cache', default=True, help="Enable cache")
@click.option('--url', default=URL_DEFAULT, help="URL")
@click.option('--expire_after', default='60 days', help=u"Cache expiration ('0': no cache, '-1': no expiration, '60 days 00:00:00': expiration delay)")
@click.option('--traceback/--no-traceback', default=False, help=u"Enable traceback")
def main(cache, url, expire_after, traceback):
    if expire_after=='-1':
        expire_after = None
    else:
        expire_after = pd.to_timedelta(expire_after, unit='s')

    if cache:
        session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=expire_after)
    else:
        session = None
    print("Using session: %s" % session)

    endpoints = ['/core-list.txt', '/catalog-list.txt']
    for endpoint in endpoints:
        url_list = URL_DEFAULT + endpoint
        response = session.get(url_list)
        for url in response.iter_lines(decode_unicode=True):
            if url != "":
                print("URL: %s" % url)
                new_url = fix_url(url)
                print("  new url: %s" % new_url)
                try:
                    datapkg = datapackage.DataPackage(new_url, session=session)
                except Exception as e:
                    if not traceback:
                        print("  exception: %s" % e)
                    else:
                        print(traceback.format_exc())
                print("")

if __name__ == '__main__':
    main()
```

**Comment by pwalsh** [comment]
@trickvi can we close this one? We have quite a lot, and growing now here https://github.com/frictionlessdata/testsuite-py

**Comment by femtotrader** [comment]
Idea here was to get remote content (and add all this content to a cache) and use this stored content to test Python DataPackage tools... not to have a hard copy of some DataPackages.

**Comment by vitorbaptista** [comment]
I like the idea of having all repositories in `github.com/datasets` as part of the test suite. That could be added to https://github.com/frictionlessdata/testsuite-py/issues, as @pwalsh said. I created an issue to track this idea in https://github.com/frictionlessdata/testsuite-py/issues/12. Meanwhile, I suggest we close this issue.
