### ISSUE TITLE
Exception "ValueError: License type is missing" shouldn't be raised

### ISSUE THREAD

**Issue by femtotrader** [trickvi/datapackage#64]
Hello,

```
datapackage.DataPackage("https://raw.githubusercontent.com/datasets/gold-prices/master/")
```

raises

```
ValueError: License type is missing
```

maybe we should expect to have set it to `None` and not raises an exception
(just send a warning using `warnings.warn`)
because we can't do anything if an exception is raised

Kind regards

**Comment by femtotrader** [comment]
An other approach is to keep exceptions being raised but have a "tolerant" mode for DataPackage which will turn such exceptions to warning message so it's still possible to work with a datapackage even if some rules are not respected (such as missing license type)

**Comment by vitorbaptista** [comment]
The new datapackage library (https://github.com/frictionlessdata/datapackage-py) doesn't raise an error if there's no license (which is the correct behaviour according to the schema). We can close this, then.
