### ISSUE TITLE
Datapackage should accept GitHub repository URL

### ISSUE THREAD

**Issue by femtotrader** [trickvi/datapackage#65]
Hello,

I think Datapackage should accept GitHub repository URL.
For example:

```
datapackage.DataPackage("https://github.com/datasets/s-and-p-500-companies")
```

raises

```
HTTPError: HTTP Error 404: Not Found
```

Instead it's necessary to do

```
datapackage.DataPackage("https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/")
```

Kind regards

**Comment by femtotrader** [comment]
This might help

```
import re

def fix_url(url, branch='master'):
    pattern = "https:\/\/github.com\/(.*)\/(.*)"
    m = re.match(pattern, url)
    if m is not None:
        (user, project) = m.groups()
        return "https://raw.githubusercontent.com/%s/%s/%s/" % (user, project, branch)

    return url

url = "https://github.com/datasets/s-and-p-500-companies"
new_url = fix_url(url)
print("  new url: %s" % new_url)
```

**Comment by femtotrader** [comment]
I noticed that

https://github.com/theodi/hot-drinks

contains `datapackage.json`

but it's available at

https://raw.githubusercontent.com/theodi/hot-drinks/gh-pages/datapackage.json

not

https://raw.githubusercontent.com/theodi/hot-drinks/master/datapackage.json

DataPackage Viewer is also not able to "discover" it without a "full" URL
http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Ftheodi%2Fhot-drinks%2Fgh-pages%2Fdatapackage.json

**Comment by vitorbaptista** [comment]
The new datapackage library (https://github.com/frictionlessdata/datapackage-py) accepts either GitHub export URLs (like https://github.com/theodi/hot-drinks/archive/gh-pages.zip) or the raw links (like https://raw.githubusercontent.com/theodi/hot-drinks/gh-pages/datapackage.json).

We don't treat the GitHub URLs specially, which is OK for me, given that the user has these other two options. I suggest we close this issue.

**Comment by trickvi** [comment]
Since the repo will be maintained by the frictionlessdata and has been solved there I'm closing this issue.
