### ISSUE TITLE
Mocklib should be imported to avoid to repeat

### ISSUE THREAD

**Issue by femtotrader** [trickvi/datapackage#66]
Hello,

I noticed that

```
if compat.is_py2:
    import mock as mocklib

if compat.is_py3:
    if compat.is_py32:
        import mock as mocklib
    else:
        from unittest import mock as mocklib
```

is both in https://github.com/femtotrader/datapackage/blob/master/tests/test_datapackage.py
and https://github.com/femtotrader/datapackage/blob/master/tests/test_resource.py

I think Mocklib should be imported in `compat.py`

https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

Kind regards

**Comment by pwalsh** [comment]
Definitely not. `compat` is for direct dependencies, not for tests.

**Comment by femtotrader** [comment]
That's ok. Maybe we can put it in an another file.

I also think that tests with cache mechanism are failing because of Mock
https://github.com/trickvi/datapackage/pull/62

Here 

```
if hasattr(descriptor, 'json'): # requests.models.Response
        return descriptor.json()
else:
   ...
```

When it's a mock it is going in "if" branch (not else)

**Comment by pwalsh** [comment]
@trickvi can we close this one?
