### ISSUE TITLE
TypeError raised when datapackage.json license field is a hash

### ISSUE THREAD

**Issue by flother** [trickvi/datapackage#68]
The [Data Packages spec states](http://dataprotocols.org/data-packages/index.html#strongly-recommended-fields) that the `license` metadata field can be either a hash or a string, but [datapackage only supports it being a string](https://github.com/trickvi/datapackage/blob/master/datapackage/datapackage.py#L52) (also mentioned in the [`DataPackage.license()` method docstring](https://github.com/trickvi/datapackage/blob/master/datapackage/datapackage.py#L226-L229)).

This means that when you attempt to load a valid data package that includes a hash in the `license` field, a `TypeError` is raised:

```
>>> import datapackage
>>> datapackage.DataPackage("https://raw.githubusercontent.com/flother/uk-general-election-2015/master/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "datapackage/datapackage.py", line 103, in __init__
    super(DataPackage, self).__init__(**descriptor)
  File "datapackage/util.py", line 42, in __init__
    self.__setattr__(key, value)
  File "datapackage/util.py", line 80, in __setattr__
    object.__setattr__(self, attribute, value)
  File "datapackage/datapackage.py", line 234, in license
    if value not in LICENSES:
TypeError: unhashable type: 'dict'
```

Tested using Python 3.4.3 and datapackage 0.5.4.

**Comment by pwalsh** [comment]
@trickvi can we close this one?

**Comment by trickvi** [comment]
Since the repo will be maintained by the frictionlessdata and developed from scratch (this therefore not being an issue) I'm closing this issue.
