### ISSUE TITLE
Example provided at https://github.com/trickvi/datapackage errors out on Windows

### ISSUE THREAD

**Issue by jamiekt** [trickvi/datapackage#69]
Hi, I tried running the example provided on Windows/python2.7 and got this:

```
>>> import datapackage
>>> datapkg = datapackage.DataPackage('http://data.okfn.org/data/cpi/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\datapackage\datapackage.py", line 101, in __init__
    self.base = args[0]
  File "C:\Python27\lib\site-packages\datapackage\util.py", line 103, in __setattr__
    ' or '.join([compat.str(s) for s in spec_type])))
```

![image](https://cloud.githubusercontent.com/assets/854953/13652784/0eb3cdde-e646-11e5-8786-8a908c1ba9f9.png)

**Comment by danfowler** [comment]
Hi @jamiekt the canonical Python library for working with Data Packages is now here: https://github.com/datapackages/datapackage-py

**Comment by jamiedh** [comment]
> Hi @jamiekt the canonical Python library for working with Data Packages is now here: https://github.com/datapackages/datapackage-py

Fantastic, thank you @danfowler . I guess the [tools doc](http://data.okfn.org/tools) needs updating, will try and get round to it later .

**Comment by jamiedh** [comment]
@danfowler Just been taking a look at this (disclaimer: I'm a python noob). What do I need to do to get this working? I downloaded the code from github (in a zip file) but when I tried to run it as per [the example](https://github.com/datapackages/datapackage-py/blob/master/README.md) I had to google for and download lots of libraries (six, requests, jsonschema, functools, tabulator etc...) Eventually i figured I was doing something, gave up, and came here to pose this question.

Do I need to run [setup.py](https://github.com/datapackages/datapackage-py/blob/master/setup.py) or something. Forgive my ignorance.

**Comment by jamiedh** [comment]
AHA, I ran `python setup.py install` and lots of things started happened. It failed, but I suspect that's because of my employer's infernal proxy.
Will try from home later.

Here's (some of) the output from the above command:

```
Installed c:\python27\lib\site-packages\datapackage-0.0.1-py2.7.egg  
Processing dependencies for datapackage==0.0.1
Searching for tabulator>=0.3.3
Reading https://pypi.python.org/simple/tabulator/
Download error on https://pypi.python.org/simple/tabulator/: [SSL: UNKNOWN_PROTO
COL] unknown protocol (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'tabulator' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: UNKNOWN_PROTOCOL] unkno
wn protocol (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for tabulator>=0.3.3
error: Could not find suitable distribution for Requirement.parse('tabulator>=0.
3.3')
```

**Comment by danfowler** [comment]
Hi @jamiedh can you raise your specific issues with the other tool on that repo: https://github.com/datapackages/datapackage-py/issues

Also, can I invite you to our general chat space for Open Knowledge Labs: https://gitter.im/okfn/chat

We can talk through things there as well :).

**Comment by jamiedh** [comment]
Certainly will do, thanks for your help so far @danfowler . I shall also engage in the chat space. I'm very excited about turning my company on to open data and this seems like a great way of going about it.

**Comment by pwalsh** [comment]
@trickvi can we close this one?
