### ISSUE TITLE
Move repo to frictionlessdata/datapackage-py

### ISSUE THREAD

**Issue by trickvi** [trickvi/datapackage#70]
The frictionlessdata project has offered to maintain this repository, albeit in a reimplemented from scratch keeping track of commit history from this repo: https://github.com/frictionlessdata/datapackage-py (already merged into master).

That should become the canonical repo for the python datapackage pypi package (and makes sense since the datapackage spec is what frictionless data is all about).

We should move all relevant issues from this repository to the new repository, close issues that don't apply and then make the relevant changes on pypi. Then close this issue and this repo.

Thank you frictionless data team for taking on the maintenance.

**Comment by trickvi** [comment]
All outstanding issues closed. I have added the frictionless data team (@vitorbaptista and okfn) to the pypi package so I'm closing this issue as it has been solved from my point of view.

**Comment by vitorbaptista** [comment]
Thanks for your help, @trickvi. There's just one last thing for this migration to be complete in my opinion: adding a deprecation notice on the README linking to https://github.com/frictionlessdata/datapackage-py.
